class Constants {
  // Notification Constants
  static const DEFAULT_TARGET = '-1';
  static const ADMIN_NEW_USER_REQUEST = '0';
  static const ADMIN_ID_VERIFICATION = '3';
  static const ADMIN_ACCOUNT_DELETED = '500';
  static const ADMIN_PHOTO_VERIFICATION = '2';
  static const ADMIN_ACCOUNT_REPORTED = '501';
  static const ADMIN_GOT_SUBSCRIPTION = '999';
  static const USER_DISCOUNT = '1';
  static const USER_CHAT_MESSAGE = '435';
  static const USER_SENT_REQUEST = '434';
  static const USER_ACCEPT_REQUEST = '443';
  static const USER_ACCOUNT_VISITED = '546';
  static const USER_NEW_MATCH = '43';
  static const USER_ACCOUNT_DELETED = '-2';
  static const USER_ACCOUNT_SUSPENDED = '-3';
  static const USER_PREMIUM_MEMBERSHIP = '99';

  // Data Constants
  static const List<String> employedInList = [
    'Private sector',
    "Government/Public sector",
    'Civil service',
    'Defence',
    'Business/Self-employed',
    'Not Working',
  ];
  static const List<String> dietList = [
    'Veg',
    'Non-Veg',
    'Occasionally Non-Veg',
    'Eggitarian',
    'Jain',
    'Vegan',
  ];
  static const List<String> maritalStatusList = [
    'Never Married',
    'Divorced',
    'Widowed',
    'Awaiting Divorce',
    'Annulled',
    'Open to all',
  ];

  static const List<String> maritalStatusListNew = [
    'Never Married',
    'Divorced',
    'Widowed',
    'Awaiting Divorce',
    'Annulled',
  ];

  static const List<String> ageList = [
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
    '41',
    '42',
    '43',
    '44',
    '45',
    '46',
    '47',
    '48',
    '49',
    '50',
    '51',
    '52',
    '53',
    '54',
    '55',
    '56',
    '57',
    '58',
    '59',
    '60',
    '61',
    '62',
    '63',
    '64',
    '65',
    '66',
    '67',
    '68',
    '69',
    '70',
    '71',
    '72',
    '73',
    '74',
    '75',
    '76',
    '77',
    '78',
    '79',
    '80',
  ];
  static const List<String> heightList = [
    "4' 5\" - 134 cm",
    "4' 6\" - 137 cm",
    "4' 7\" - 139 cm",
    "4' 8\" - 142 cm",
    "4' 9\" - 144 cm",
    "4' 10\" - 147 cm",
    "4' 11\" - 149 cm",
    "5' 0\" - 152 cm",
    "5' 1\" - 154 cm",
    "5' 2\" - 157 cm",
    "5' 3\" - 160 cm",
    "5' 4\" - 162 cm",
    "5' 5\" - 165 cm",
    "5' 6\" - 167 cm",
    "5' 7\" - 170 cm",
    "5' 8\" - 172 cm",
    "5' 9\" - 175 cm",
    "5' 10\" - 177 cm",
    "5' 11\" - 180 cm",
    "6' 0\" - 182 cm",
    "6' 1\" - 185 cm",
    "6' 2\" - 187 cm",
    "6' 3\" - 190 cm",
    "6' 4\" - 193 cm",
    "6' 5\" - 195 cm",
    "6' 6\" - 198 cm",
    "6' 7\" - 200 cm",
    "6' 8\" - 203 cm",
    "6' 9\" - 205 cm",
    "6' 10\" - 208 cm",
    "6' 11\" - 210 cm",
    "7' 0\" - 213 cm",
  ];

  static const List<String> genderList = [
    'Male',
    'Female',
  ];
  static const List<String> qualificationList = [
    "Ph.D.",
    "DM",
    "Fellow of National Board (FNB)",
    "IAS",
    "IPS",
    "IRS",
    "IES",
    "IFS",
    "CA",
    "ICWA",
    "CS",
    "CFA (Chartered Financial Analyst)",
    "M.Phil.",
    "MCom",
    "M.Sc.",
    "M.A.",
    "M.Ed.",
    "MLIS",
    "MSW",
    "MFA",
    "M.Des",
    "M.S.(Engg.)",
    "M.Arch.",
    "MCA",
    "PGDCA",
    "ME",
    "M.Tech.",
    "M.Sc. IT / Computer Science",
    "M.L.",
    "LL.M.",
    "MHM  (Hotel Management)",
    "MBA",
    "PGDM",
    "MHRM (Human Resource Management)",
    "MFM (Financial Management)",
    "MHA / MHM (Hospital Administration)",
    "MD / MS (Medical)",
    "MDS",
    "MVSc",
    "MCh",
    "DNB",
    "B.Phil.",
    "B.Com.",
    "B.Sc.",
    "B.A.",
    "B.Ed.",
    "Aviation Degree",
    "BFA",
    "BLIS",
    "B.S.W",
    "B.M.M.",
    "BFT",
    "B.Des",
    "BCA",
    "Aeronautical Engineering",
    "B.Arch",
    "B.Plan",
    "BE",
    "B.Tech.",
    "B.Sc IT/ Computer Science",
    "B.S.(Engineering)",
    "BGL",
    "B.L.",
    "LL.B.",
    "BHM (Hotel Management)",
    "BBA",
    "BFM (Financial Management)",
    "BHA / BHM (Hospital Administration)",
    "MBBS",
    "BDS",
    "BVSc",
    "BHMS",
    "B.A.M.S.",
    "BSMS",
    "BUMS",
    "Trade School",
    "Diploma",
    "Polytechnic",
    "Higher Secondary School / High School",
    "BPT",
    "BPharm",
    "B.Sc. Nursing",
    "MPT",
    "M.Pharm",
    "Others",
  ];
  static const List<String> designationList = [
	  'Accounts / Finance Professional',
    'Actor / Model',
    'Administrative Professional',
    'Advertising / PR Professional',
    'Agent / Broker / Trader',
    'Agriculture &amp; Farming Professional',
    'Air Force',
    'Air Hostess / Flight Attendant',
    'Airline Professional',
    'Analyst',
    'Animator',
    'Architect',
    'Army',
    'Artist',
    'Arts &amp; Craftsman',
    'Associate',
    'Auditor',
    'Banking Service Professional',
    'Beautician',
    'BPO / KPO / ITes Professional',
    'Builder',
    'Business Development Professional',
    'Business Owner / Entrepreneur',
    'Chartered Accountant',
    'Chef / Cook',
    'Chemist',
    'Civil Engineer',
    'Civil Services (IAS / IES / IFS / IPS / IRS)',
    'Clerk',
    'CNC Operator',
    'Company Secretary',
    'Consultant',
    'Content Writer',
    'Contractor',
    'Corporate Communication',
    'Corporate Planning',
    'Customer Service Professional',
    'CXO / President, Director, Chairman',
    'Cyber / Network Security',
    'Data Analyst',
    'Data Scientist',
    'Defence Services (Others)',
    'Dentist',
    'Designer',
    'Designer',
    'Designer (others)',
    'Dietician / Nutritionist',
    'Distributor',
    'Doctor',
    'Driver',
    'Education Professional',
    'Electronics / Telecom Engineer',
    'Engineer - Non IT',
    'Entertainment Professional',
    'Event Management Professional',
    'Executive',
    'Fashion Designer',
    'Financial Accountant',
    'Financial Analyst / Planning',
    'Fitness Professional',
    'Freelancer',
    'Hair Stylist',
    'Hardware Professional',
    'Healthcare Professional',
    'Horticulturist',
    'Hotel / Hospitality Professional',
    'Human Resources Professional',
    'Interior Designer',
    'Investment Professional',
    'Jewellery designer',
    'Jewellery maker',
    'Jewellery seller',
    'Journalist',
    'Lab Technician',
    'Law Enforcement Officer',
    'Lawyer &amp; Legal Professional',
    'Legal Assistant',
    'Librarian',
    'Makeup Artist',
    'Manager',
    'Mariner / Merchant Navy',
    'Marketing Professional',
    'Mechanic',
    'Mechanical / Production Engineer',
    'Media Professional',
    'Medical Representative',
    'Medical Transcriptionist',
    'Musician',
    'Navy',
    'Network Engineer',
    'Nurse',
    'Officer',
    'Operations Management',
    'Paramedical Professional',
    'Paramilitary',
    'Pharmacist',
    'Photo / Videographer',
    'Physiotherapist',
    'Pilot',
    'Police',
    'Politician',
    'Product Manager',
    'Product Manager - Non IT',
    'Professor / Lecturer',
    'Program Manager',
    'Project Manager',
    'Project Manager - Non IT',
    'Psychologist',
    'Quality Assurance Engineer',
    'Quality Assurance Engineer - Non IT',
    'Research Assistant',
    'Research Scholar',
    'Restaurant / Catering Professional',
    'Retired',
    'Sailor',
    'Sales Professional',
    'Scientist / Researcher',
    'Secretary / Front Office',
    'Security Professional',
    'Self Employed',
    'Senior Manager / Manager',
    'Singer',
    'Social Worker / Volunteer / NGO',
    'Software Consultant',
    'Software Professional',
    'Sportsperson',
    'Student',
    'Subject Matter Expert',
    'Supervisor',
    'Surgeon',
    'Surveyor',
    'Tailor',
    'Teaching / Academician',
    'Technician',
    'Therapist',
    'Training Professional',
    'Transportation / Logistics Professional',
    'Travel Professional',
    'UI / UX Designer',
    'Veterinary Doctor',
    'VP / AVP / GM / DGM / AGM',
    'Web / Graphic Designer',
    'Writer',
    'Not working',
    'Others',
  ];
  static const List<String> incomeList = [
    'Not Working',
    '< 1 lakhs',
    '1-3 lakhs',
    '3-5 lakhs',
    '5-7 lakhs',
    '7-9 lakhs',
    '9-10 lakhs',
    '10-15 lakhs',
    '15-20 lakhs',
    '20-25 lakhs',
    '> 30 lakhs',
  ];

  static const List<String> fatherStatusList = [
    'Employed',
    'Business',
    'Retired',
    'Not Employed',
    'Passed Away',
  ];
  static const List<String> motherTongueList = [
    "Hindi",
    "English",
    "Assamese",
    "Bangla",
    "Bodo",
    "Dogri",
    "Gujarati",
    "Kashmiri",
    "Kannada",
    "Konkani",
    "Maithili",
    "Malayalam",
    "Manipuri",
    "Marathi",
    "Nepali",
    "Oriya",
    "Punjabi",
    "Tamil",
    "Telugu",
    "Santali",
    "Sindhi",
    "Urdu",
  ];
  static const List<String> motherStatusList = [
    'Home Queen', // 'Homemaker'
    'Employed',
    'Business',
    'Retired',
    'Passed Away',
  ];
  static const List<String> familyTypeList = [
    'Joint',
    'Nuclear',
  ];
  static const List<String> manglikList = [
    'Manglik',
    'Non Manglik',
    'Anshik Manglik',
    'Don\'t know',
  ];

  static const List<String> profileList = [
    'Self',
    'Son',
    'Daughter',
    'Brother',
    'Sister',
    'Friend',
    'Relative',
  ];

  static const List<String> religionList = [
    'Awadhiya',
    'Ayodhyawashi',
    'Brahmin',
    'Bundelkhandi',
    'Bundelkhandi Kshatriya',
    'Dalya',
    'Deshwall',
    'Kanaujiya',
    'Kannokiya',
    'Kanoja',
    'Katalpuri',
    'Khargapuriya',
    'Kshatriya',
    'Kshatriya (Non Maidh)',
    'Mahor',
    'Maidh Kshatriya',
    'Maidh Kshatriya suryavanshi',
    'Maidh Rajput',
    'Malvi',
    'Meerakhpuria',
    'Mevadi',
    'Narvariya',
    'Negapura Maidh Kshatriya',
    'Nekpuriya',
    'Pardesi',
    'Punjabi',
    'Purniya',
    'Rajput',
    'Rastogi',
    'Sekhawati',
    'Shrimali',
    'Vaishnav',
  ];

  static const List<String> bloodGroupList = [
    'A+',
    'A-',
    'B+',
    'B-',
    'AB+',
    'AB-',
    'O-'
  ];

  static const List<String> livingTogetherList = [
    'Yes. Living together',
    'No',
    'Yes. Not living together'
  ];

  static const List<String> childrenList = [
    '1',
    '2',
    '3',
    'More than 3'
  ];

  static const List<String> countryList = [
    'India',
    'Foreign',
  ];
  static const List<String> dayList = [
    '01',
    '02',
    '03',
    '04',
    '05',
    '06',
    '07',
    '08',
    '09',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
  ];
  static const List<String> monthList = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ];

  static const List<String> familyValues = [
    'Traditional',
    'Moderate',
    'Liberal',
  ];
  static const List<String> afluenceList = [
    'Affluent',
    'Upper Middle Class',
    'Middle Class',
    'Lower Middle Class'
  ];

  static const List<String> communityList = [
    'Brahmin',
    'Jain',
    'Rajput',
  ];
  static const List<String> visibilityList = [
    'All Member',
    'Premium Members only',
    'Connected Members',
  ];

  static const List<String> reportReasons = [
    'Fake / Misleading profile Information',
    'Multiple Profiles',
    'Phone number is incorrect',
    'Photos are fake or abscene',
    'Has sent abusive chats',
    'Is already married / engaged',
    'Asking for money / scammer',
    'Other misuse reasons',
  ];

  static const List<String> statesList = [
    'Andaman and Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarth',
    'Chhattisgarh',
    'Dadra and Nagar Haveli',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Ladakh',
    'Lakshadweep',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Ponducherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal'
  ];

  static const List<String> hobbies = [
    "Acting",
    "Animal breeding",
    "Art / Handicraft",
    "Astrology / Palmistry / Numerology",
    "Astronomy",
    "Bird watching",
    "Collectibles",
    "Cooking",
    "Dancing",
    "DIY(do it yourself) projects",
    "Film-making",
    "Fishing",
    "Gardening / Landscaping",
    "Graphology",
    "Ham radio",
    "Home / Interior decoration",
    "Hunting",
    "Model building",
    "Painting / Drawing",
    "Photography",
    "Playing musical instruments",
    "Singing",
    "Solving Crosswords, Puzzles"
  ];
  static const List<String> intrests = [
    "Alternativehealing",
    "Bikes / Cars",
    "Blogging",
    "Clubbing",
    "Driving",
    "Eating out",
    "Health & Fitness",
    "Hiking / Camping",
    "Learning new languages",
    "Listening to music",
    "Mehendi Designing",
    "Movies",
    "Museums / Galleries / Exhibitions",
    "Nature",
    "Net surfing",
    "Pets",
    "Politics",
    "Reading / Book clubs",
    "Religion",
    "Shopping",
    "Sports - Indoor",
    "Sports - Outdoor",
    "Stitching",
    "Technology",
    "Theatre",
    "Travel / Sightseeing",
    "Trekking / Adventure sports",
    "Video / Computer games",
    "Volunteering / Social Service",
    "Watching television",
    "Wine tasting",
    "Writing",
    "Yoga / Meditation",
  ];
  static const List<String> favMusic = [
    "Acid Rock / Hard Rock",
    "Alternative Music",
    "Bhajans / Devotional",
    "Bhangra",
    "Blues",
    "Christian / Gospel / Blue Grass",
    "Classical - Carnatic",
    "Classical - Hindustani",
    "Classical - Opera",
    "Classical - Western",
    "Country Music",
    "Disco",
    "Folk",
    "Ghazals",
    "Heavy Metal",
    "Hip-Hop",
    "House Music",
    "Indipop",
    "Instrumental - Indian",
    "Instrumental - Western",
    "Jazz",
    "Latest film songs",
    "Latin Music",
    "New Age Music",
    "Old film songs",
    "Pop",
    "Qawalis",
    "R&B / Soul",
    "Rap",
    "Reggae",
    "Remixes",
    "Soft Rock",
    "Sufi music",
    "Techno / Trance",
    "Western Country Music",
    "World Music",
    "Enjoy most forms of music",
  ];
  static const List<String> sportsFitnes = [
    "Aerobics",
    "Athletics",
    "Badminton",
    "Baseball",
    "Basketball",
    "Billiards / Snooker / Pool",
    "Bowling",
    "Boxing / Wrestling",
    "Card games",
    "Carrom",
    "Chess",
    "Cricket",
    "Cycling",
    "Football / Soccer",
    "Golf",
    "Gym workouts / Weight training",
    "Hockey",
    "Horseback Riding",
    "Jogging / Walking / Running",
    "Martial Arts",
    "Motor Racing",
    "Polo",
    "Rugby",
    "Sailing / Boating / Rowing",
    "Scrabble",
    "Scuba Diving",
    "Shooting",
    "Skating / Snowboarding / Skiing",
    "Squash",
    "Swimming / Water sports",
    "Table-tennis",
    "Tennis",
    "Trekking / Adventure sports",
    "Volleyball",
    "Weight training",
    "Winter / Rink sports",
    "Yoga / Meditation",
  ];
  static const List<String> favCousine = [
    "American",
    "Arabic",
    "Bengali",
    "Chinese",
    "Continental",
    "Fast food",
    "Gujarati",
    "Italian",
    "Japanese",
    "Konkan",
    "Lebanese",
    "Mexican",
    "Moghlai",
    "North Indian",
    "Persian",
    "Punjabi",
    "Rajasthani",
    "Seafood",
    "Sindhi",
    "Soul Food",
    "South Indian",
    "Spanish",
    "Thai",
  ];
  static const List<String> dressStyle = [
    "Business casual - semi-formal office wear",
    "Casual - usually in jeans and T-shirts",
    "Classic Indian - typically Indian formal wear",
    "Classic Western - typically western formal wear",
    "Designer - only leading brands will do",
    "Trendy - in line with the latest fashion",
  ];

  static const List<String> hourList = [
    '01',
    '02',
    '03',
    '04',
    '05',
    '06',
    '07',
    '08',
    '09',
    '10',
    '11',
    '12',
  ];
  static const List<String> minuteList = [
    '01',
    '02',
    '03',
    '04',
    '05',
    '06',
    '07',
    '08',
    '09',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
    '41',
    '42',
    '43',
    '44',
    '45',
    '46',
    '47',
    '48',
    '49',
    '50',
    '51',
    '52',
    '53',
    '54',
    '55',
    '56',
    '57',
    '58',
    '59',
    '60'
  ];
  static const List<String> AmPmList = [
    'AM',
    'PM'
  ];
}
